OBJ = 	chase.o \
	cl_demo.o \
	cl_input.o \
	cl_main.o \
	cl_parse.o \
	cl_tent.o \
	cmd.o \
	common.o \
	console.o \
	crc.o \
	cvar.o \
	host.o \
	host_cmd.o \
	keys.o \
	mathlib.o \
	menu.o \
	net_dgrm.o \
	net_loop.o \
	net_main.o \
	net_vcr.o \
	pr_cmds.o \
	pr_edict.o \
	pr_exec.o \
	r_part.o \
	sbar.o \
	sv_main.o \
	sv_move.o \
	sv_phys.o \
	sv_user.o \
	view.o \
	wad.o \
	world.o \
	zone.o \
	sys_ctr.o \
	d_edge.o \
	d_fill.o \
	d_init.o \
	d_modech.o \
	d_part.o \
	d_polyse.o \
	d_scan.o \
	d_sky.o \
	d_sprite.o \
	d_surf.o \
	d_vars.o \
	d_zpoint.o \
	draw.o \
	model.o \
	nonintel.o \
	r_aclip.o \
	r_alias.o \
	r_bsp.o \
	r_draw.o \
	r_edge.o \
	r_efrag.o \
	r_light.o \
	r_main.o \
	r_misc.o \
	r_sky.o \
	r_sprite.o \
	r_surf.o \
	r_vars.o \
	screen.o \
	snd_dma.o \
	snd_mix.o \
	snd_mem.o \
	snd_ctr.o \
	vid_ctr.o \
	net_bsd.o \
	net_udpctr.o \
	in_ctr.o \
	cd_null.o \
	lcd.o

CFLAGS =  -Og -g3 -DPC -DUSE_SDL
.SUFFIXES: .c .o

# プライマリターゲット
a.out: $(OBJ)
	$(CC) $^ -lm -lSDL2

# サフィックスルール
.c.o:
	gcc $(CFLAGS) -c $<
